[workspace]
members = [
    "conjure-codegen",
    "conjure-error",
    "conjure-http",
    "conjure-object",
    "conjure-rust",
    "conjure-serde",
    "conjure-test",
]

exclude = [
    "example-api",
]
