[package]
name = "conjure-rust"
version = "0.3.10"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
structopt = "0.2"

conjure-codegen = { version = "0.3.10", path = "../conjure-codegen" }
