[package]
name = "conjure-http"
version = "0.3.10"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"
license = "Apache-2.0"
description = "HTTP interfaces for generated Conjure services"
repository = "https://github.com/palantir/conjure-rust"
readme = "../README.md"

[dependencies]
http = "0.1"
lazy_static = "1.0"
serde = "1.0"

conjure-error = { version = "0.3.10", path = "../conjure-error" }
conjure-object = { version = "0.3.10", path = "../conjure-object" }
conjure-serde = { version = "0.3.10", path = "../conjure-serde" }
