[package]
name = "conjure-error"
version = "0.4.5"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Runtime support for generated Conjure errors"
repository = "https://github.com/palantir/conjure-rust"
readme = "../README.md"

[dependencies]
backtrace = "0.3"
parking_lot = "0.9"
serde = "1.0"
serde-value = "0.6"
uuid = { version = "0.7", features = ["v4"] }

conjure-object = { version = "0.4.5", path = "../conjure-object" }
