[package]
name = "conjure-object"
version = "0.3.10"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Runtime support for generated Conjure objects"
repository = "https://github.com/palantir/conjure-rust"
readme = "../README.md"

[dependencies]
base64 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.0"
regex = "1.0"
serde = "1.0"
serde-value = "0.5"
serde_bytes = "0.10"
uuid = { version = "0.7", features = ["serde"] }

[dev-dependencies]
proptest = "0.7"
