[package]
name = "conjure-object"
version = "0.5.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Runtime support for generated Conjure objects"
repository = "https://github.com/palantir/conjure-rust"
readme = "../README.md"

[dependencies]
base64 = "0.11"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.0"
regex = { version = "1.3", default-features = false, features = ["std"] }
serde = "1.0"
serde-value = "0.6"
serde_bytes = "0.11"
uuid = { version = "0.7", features = ["serde"] }

[dev-dependencies]
proptest = "0.9"
